### ISSUE TITLE
The code is not working.

### ISSUE THREAD

**Issue by JafferWilson** [shrestha-bikash/Personality-Prediction#1]
Hello,
 have tried to run your code by clicking on the index .htm, I got the blue screen page, but after clicking on the Facebook button nothing happens. Please let me know what I am making mistake?

**Comment by shrestha-bikash** [comment]
This repo has not been updated. Please try this [https://github.com/shrestha-bikash/major_project](https://github.com/shrestha-bikash/major_project) repo, it has fully updated code.

**Comment by JafferWilson** [comment]
Sure.. Let me check..

**Comment by JafferWilson** [comment]
@shrestha-bikash The repository is not working properly as I have gone through it. Please can you check the issue there? As soon as you reply my queries there I will close the issue here.
